//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_BasicInfo
    {
        public int EmpId { get; set; }
        public string EmpFName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpUserName { get; set; }
        public Nullable<int> EmpCell { get; set; }
        public string EmpEmail { get; set; }
        public string EmpImage { get; set; }
        public Nullable<int> EmpDesignationId { get; set; }
        public Nullable<int> EmpDeptId { get; set; }
        public string EmpIdNumber { get; set; }
        public string EmpJoiningDate { get; set; }
        public Nullable<int> EmpTypeId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SetUpBy { get; set; }
        public Nullable<System.DateTime> SetUpDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
