//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_MaintenanceInfo
    {
        public string MaintainceId { get; set; }
        public string MaintainceCode { get; set; }
        public string ItemId { get; set; }
        public Nullable<System.DateTime> LastMaintainceDate { get; set; }
        public string MaintainceYear { get; set; }
        public string MaintainceDetails { get; set; }
        public string MaintainceLocation { get; set; }
        public string DefectInfo { get; set; }
        public string MaintainceTypeId { get; set; }
        public Nullable<System.DateTime> NextMaintainceSchadule { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SetUpBy { get; set; }
        public Nullable<System.DateTime> SetUpDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsBackup { get; set; }
        public string DerectorateId { get; set; }
        public Nullable<System.DateTime> LastBackupDate { get; set; }
    }
}
