//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_WeaponsInfo
    {
        public string WeaponsInfoId { get; set; }
        public string WeaponsTypeId { get; set; }
        public string NameOfWeaponsId { get; set; }
        public string TrackingNo { get; set; }
        public string WeaponsModel { get; set; }
        public string RegistrationNo { get; set; }
        public string ManufactureYear { get; set; }
        public string FiscalYearId { get; set; }
        public string OriginCountryId { get; set; }
        public string ManufactureCountryId { get; set; }
        public string Purpose { get; set; }
        public string ProcurementYear { get; set; }
        public string WarrantyPeriod { get; set; }
        public string PriceTypeId { get; set; }
        public string UnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string QuantityCategoryId { get; set; }
        public string TotalPrice { get; set; }
        public string LocalAgentId { get; set; }
        public string PrincipalAgentId { get; set; }
        public string ManufactureAgentId { get; set; }
        public string Image { get; set; }
        public string DepotId { get; set; }
        public string ProcurementCatId { get; set; }
        public string WareHouseId { get; set; }
        public string BinLocationId { get; set; }
        public string TechnicalSpec { get; set; }
        public string Weight { get; set; }
        public string Dimention { get; set; }
        public string MaximumRange { get; set; }
        public string EffectiveRange { get; set; }
        public string MuzzeleVelocity { get; set; }
        public string BarrelLife { get; set; }
        public string OperatingTemp { get; set; }
        public string StoringTemp { get; set; }
        public string PreservatingTemp { get; set; }
        public string StatusId { get; set; }
        public Nullable<System.DateTime> DateAfterAcceptance { get; set; }
        public string WorkOrderNumber { get; set; }
        public string Remarks { get; set; }
        public string MissilTypeId { get; set; }
        public string SerialNumber { get; set; }
        public string ShelfLifeOfWeapon { get; set; }
        public string ShelfLifeOfLauncher { get; set; }
        public string PreparationTimeId { get; set; }
        public string CombatDuration { get; set; }
        public string Caliber { get; set; }
        public string AmmunitationTypeId { get; set; }
        public string LotNumberId { get; set; }
        public string ProofFiringStatus { get; set; }
        public Nullable<System.DateTime> ProofFiringDate { get; set; }
        public string Humidity { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsMaintaince { get; set; }
        public Nullable<int> SetUpBy { get; set; }
        public Nullable<System.DateTime> SetUpDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsBackup { get; set; }
        public string DerectorateId { get; set; }
        public string Brand { get; set; }
        public Nullable<System.DateTime> LastBackupDate { get; set; }
    }
}
