//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MaintainceStatus_c_
    {
        public string MaintainceStatusId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
