//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Menu
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> SubParentId { get; set; }
        public string MenuName { get; set; }
        public string MenuClass { get; set; }
        public string MenuId { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SortingOrderHelper { get; set; }
        public Nullable<int> SetUpUserId { get; set; }
        public Nullable<System.DateTime> SetUpDateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
