//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_ShipOrDepotInfo
    {
        public string ShipOrDepotId { get; set; }
        public string ShipOrDepotCode { get; set; }
        public string AuthorityId { get; set; }
        public Nullable<int> ShipDepotCategory { get; set; }
        public string ShipDepotName { get; set; }
        public Nullable<System.DateTime> DateOfCommmisson { get; set; }
        public string WTCallSign { get; set; }
        public string CapabilityOfWeaponsId { get; set; }
        public Nullable<int> TypeOfShip { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string FaxNo { get; set; }
        public string WebAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SetUpBy { get; set; }
        public Nullable<System.DateTime> SetUpDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsBackup { get; set; }
        public string DerectorateId { get; set; }
    }
}
