//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string SessionKey { get; set; }
        public string UserFullName { get; set; }
    }
}
