//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNAMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Inspection
    {
        public string InspectionId { get; set; }
        public string ProgramId { get; set; }
        public string DepotId { get; set; }
        public string ItemCategoryId { get; set; }
        public string ItemId { get; set; }
        public Nullable<System.DateTime> LastInspectionDate { get; set; }
        public Nullable<System.DateTime> NextInspectionDate { get; set; }
        public Nullable<System.DateTime> INstallDate { get; set; }
        public string InstallBy { get; set; }
        public string InstallAt { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string InspectionMethod { get; set; }
        public string InspectionBy { get; set; }
        public string Commence { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SetUpBy { get; set; }
        public Nullable<System.DateTime> SetUpDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsBackup { get; set; }
        public string DerectorateId { get; set; }
    }
}
